kind: 'CDN'
version: '1'
data:
  originSelectors:
    rules:
      - name: route-to-first-edge-function
        when: 
          allOf:
            - reqProperty: path 
              equals: "/blog/first-post"
            - reqProperty: domain
              like: "main--eds-aem--jjbca"      
        action:
          type: selectAemOrigin
          originName: edgefunction-location-flag
          skipCache: true
