kind: 'CDN'
version: '1'
data:
  originSelectors:
    rules:
      # Route /blog/* to your edge function
      - name: route-blog-to-edge-function
        when:
          allOf:
            - reqProperty: domain
              equals: eds.labulle.in
            - reqProperty: path
              equals: "/hello-world"
        action:
          type: selectAemOrigin
          originName: edgefunction-location-flag
          skipCache: true

      # Everything else → EDS origin
      - name: fallback-to-eds
        when:
          reqProperty: domain
          equals: eds.labulle.in
        action:
          type: selectOrigin
          originName: eds-origin

    origins:
      - name: eds-origin
        domain: eds.labulle.in
        forwardHost: false